server:
  port: 8091
spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
          filters:
            - AddRequestHeader=source, gateway
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    #设置应用的名称
    name: dubbo-springboot-consumer
  #指定使用Dubbo协议，且端口设置为-1，表示随机分配可用端口
  protocol:
    name: dubbo
    port: -1
  registry:
    #配置注册中心为Nacos
    id: nacos-registry
    address: nacos://localhost:8848
