server:
  port: 8091
spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
          filters:
            - AddRequestHeader=source, gateway
#        - id: api_route
#          uri: http://116.196.68.160:8123
#          predicates:
#            - Path=/api/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    #设置应用的名称
    name: dubbo-springboot-consumer
    #qos监控服务是否启动
#    qos-enable: true
  #指定使用Dubbo协议，且端口设置为-1，表示随机分配可用端口
  protocol:
    name: dubbo
    port: -1
  registry:
    #配置注册中心为Nacos
    id: nacos-registry
#    address: nacos://172.30.0.3:8848
    address: nacos://localhost:8848
#    172.30.0.3
#    username: nacos
#    password: nacos
